sbatch --export=ALL,genes="PPAT" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="SREBF1" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="NDUFS2" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="WRN" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="NDUFB9" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="MRPL46" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="MED24" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="EP300" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="COA6" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="KRTAP5-9" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="COX4I1" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="PSPC1" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="COX18" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="NDUFB11" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="EED" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="ZC3H13" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="CHKA" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="GOLGA6L6" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="NDUFAF1" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="F3" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="NDUFB2" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="NDUFC2" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="PDE12" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="VAC14" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="COX6A1" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="OR6C6" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="HIST1H1E" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="MRPL30" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="MED23" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="WASHC2C" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="GCSH" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="CORO6" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="ZBTB39" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="DHX29" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="NDUFA3" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="DTD2" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="DHFR2" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="TIMMDC1" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="TRIM9" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="COA3" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="SPICE1" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="NOA1" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="OST4" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="YAF2" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="PRUNE1" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="ZNF714" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="IFT57" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="BRAT1" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="MTERF3" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="WWTR1" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="IRS2" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="EPC2" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="ZNF217" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="SETD5" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="CT45A7" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="SOX10" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="NDE1" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="KIF2C" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="TFAP4" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="CDK6" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="KDSR" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="UBE2O" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="ZNF511" screen_pan_can_KMT2D_reverse_genes_one.sh
sbatch --export=ALL,genes="PI4KB" screen_pan_can_KMT2D_reverse_genes_one.sh
